FROM python:3.7
RUN apt-get update && apt-get install -y git
RUN mkdir /data
WORKDIR /home
RUN git clone https://github.com/BrkRaw/bruker.git
WORKDIR /home/bruker
RUN git remote rename origin bruker
WORKDIR /
RUN python -m pip install -e /home/bruker

CMD echo '--------------------'; \
    echo 'To use the bids converter:'; \
    echo 'first run bids_helper'; \
    echo 'brkraw bids_helper <input dir> <output filename> -j'; \
    echo 'second, run converter'; \
    echo 'brkraw bids_convert <input dir> <BIDS datasheet.xlsx> -j <JSON syntax template.json> -o <output dir>';\
    echo '--------------------'; \
    bash

