# default configuration for brkraw
snippets:
  repo:
  - name: brkraw-snippets
    url: https://github.com/brkraw/brkraw-snippets.git
    plugin:
      path: plugin
      template: 
      - myplugin
    preset:
      path: preset
      template: 
      - mypreset
    spec:
      path: spec
    recipe:
      path: recipe

studyinfo:
  recipe: default

app:
  tonifti:
    output_filename: 
      format: <id>_<method>_<scan_id>_<reco_id>
      filter: