plugin:
  repo:
  - name: brkraw-snippets
    url: https://github.com/brkraw/brkraw-snippets.git
    path: plugin
    preset:
      path: preset
    spec:
      path: spec
    recipe:
      path: recipe
  
app:
  tonifti:
    output_filename:
      recipy: "@brkraw-snippets,better-tonifti:studyinfo"
      format: <id>_<method>_<scan_id>_<reco_id>
      spec: null
    studyinfo:
      recipe: brkraw-snippets:studyinfo #<repo name>:<recipe name>:<recipe version>