name: test

on:
  # this workflow triggered on below condition [push, pull_request]
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

# cancel previous similar workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_cli:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Set up python ${{ matrix.python-version }}

      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Version and help
      run: |
        brkraw --version
        brkraw --help

    - name: "smoke end-to-end test: use CLI on tutorial data"
      run: make demo
        

  test_tutorial:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Set up python ${{ matrix.python-version }}

      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install .[SimpleITK]

    - name: Install tutorial
      run: make tests/tutorials

    - name: Test tutorial notebook
      run: |
        python -m pytest --nbmake tests/tutorials/JupyterNotebooks/01_GettingStarted.ipynb